### ISSUE TITLE
Migrate Implementation Guidance from POD 

### ISSUE THREAD

**Issue by crysacarter** [GSA/resources.data.gov#106]
Implementation Guidance https://project-open-data.cio.gov/implementation-guide/

https://resources.data.gov/guidance/ still links to POD

**Comment by hkdctol** [comment]
@crysacarter On this one, it is made clear that what is provided is guidance on the 2013 policy. I would recommend creating a version of the guidance on resources.data.gov and linking.

**Comment by juliaklindpaintner** [comment]
Seems like this issue has been resolved.
