### ISSUE TITLE
Migrate Licensing policies, principles, and resources from POD 

### ISSUE THREAD

**Issue by crysacarter** [GSA/resources.data.gov#107]
https://resources.data.gov/skill-builders/

Licencing policies principles and resources https://project-open-data.cio.gov/licensing-resources/

**Comment by hkdctol** [comment]
@crysacarter most of the content is very dated. I would recommend keeping a copy of the text and links on the POD version, and removing the link from resources.data.gov for now.

**Comment by crysacarter** [comment]
https://docs.google.com/document/d/1EsXJotKXr25A61KHZk8yelB_egRbdEFbHSOF0wqlxfA/edit?usp=sharing

content saved

**Comment by hkdctol** [comment]
Confirmed work was done.
