### ISSUE TITLE
Citation for requirement under OPEN Gov Data Act?

### ISSUE THREAD

**Issue by h-m-f-t** [GSA/resources.data.gov#124]
On the [how-to-get-your-open-data-on-datagov](https://resources.data.gov/tools/how-to-get-your-open-data-on-datagov/#federal-data-with-project-open-data) page, it says:
> Under the OPEN Government Data Act and the Open Data Policy, federal agencies are required to publish an enterprise data inventory, provided as a data.json file,using the standard Project Open Data metadata schema. The machine readable listing, as a standalone JSON file on the agency’s website at `agency.gov/data.json`.

I quickly eyeballed those two docs to see if there was something explicit requiring placement of e.g., JSON files at `/data.json` and didn't see anything. Is there something more direct that could be cited to in statute or guidance?

(And if you choose not to link to it, that's ok, though I'd still like to know!)

**Comment by rebeccawilliams** [comment]
@adborden This the POD m-13-13 implementation guidance, is that ported over?

**Comment by hkdctol** [comment]
I would close this for now. It has not been addressed in the draft guidance that we've seen so far. We commented on this and we'll see what the final guidance from OMB says and take it from there.
