### ISSUE TITLE
upgrade uswds-gulp

### ISSUE THREAD

**Issue by cantsin** [GSA/resources.data.gov#156]
Recent updates to https://github.com/uswds/uswds-gulp broke builds on Federalist. Turns out that this dependency wasn't locked to a specific commit, It just pulled from master. Fixing this involved pinning the sha1 hash specifically (see 9199c461cc4b57f028782ac75287d9a3c83ea869)

As a short term fix, I have locked the dependency to this commit (made on Jun 6, 2019), but we really should take the time to investigate and upgrade cleanly. This will involve removing `gulpfile.js`, adding in a new `gulpfile-uswds.js` file and re-configuring this file. I haven't investigated much beyond this due to lack of time.

**Comment by adborden** [comment]
Fixed in https://github.com/GSA/resources.data.gov/pull/318
