### ISSUE TITLE
Add GS1 US to standards page on https://resources.data.gov/standards/

### ISSUE THREAD

**Issue by gs1us** [GSA/resources.data.gov#190]
Hello,
We are interested in adding GS1 US to the communities section of the Standards Page (https://resources.data.gov/standards/). Please see the suggested content below.  Let me know if you need anything else.  Thank you! 

GS1 US®, (https://www.gs1us.org/) is a not-for-profit data standards and unique identification organization that facilitates industry collaboration to help improve supply chain visibility and efficiency through the use of GS1 Standards, the most widely-used supply chain standards system in the world.

**Comment by hkdctol** [comment]
Closing this -- I think we discussed at last meeting it's not relevant.
