### ISSUE TITLE
Link to OPEN Government Data Act

### ISSUE THREAD

**Issue by adborden** [GSA/resources.data.gov#250]
When searching for OPEN Government Data Act, no relevant results show up.

**Comment by adborden** [comment]
Since this is part of the Evidence Act (title II), we could attach this to the Evidence Act. A citation or a one-sentence summary should be enough.

**Comment by hkdctol** [comment]
@adborden would creating links to the legislation for OPEN Government Data Act where it appears on https://resources.data.gov/about/about-this-repository/ result in search results? Or does something else have to be done. In any event, @crysacarter can you add links on that page where the "OPEN Government Data Act" term appears?

**Comment by crysacarter** [comment]
PR #272

**Comment by adborden** [comment]
I don't think it will improve the search results, but it's a good change. The Evidence Act is already listed and mentions OPEN Government Data Act. I took another look at the search results and I think this is more an issue with search.gov/Bing. Idk, I'm fine to close this.
