### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by juliaklindpaintner** [GSA/resources.data.gov#34]
Current Favicon is from the PRA website—change to the ring graphic currently displayed.

**Comment by adborden** [comment]
@philipashlock where did you get the ring graphic?

**Comment by juliaklindpaintner** [comment]
@adborden It's here! https://github.com/GSA/resources.data.gov/blob/master/pages/assets/img/ring.png

**Comment by juliaklindpaintner** [comment]
This will be fixed with the new version of r.d.g
