### ISSUE TITLE
Edit intro language

### ISSUE THREAD

**Issue by hkdctol** [GSA/resources.data.gov#37]
For the main page, to reflect purposes broader than open data, per meeting July 17, suggested revision:

Resources.data.gov is an effort by the Office of Management and Budget, the Office of Government Information Services of the National Archives, and the General Services Administration to provide an online repository of guidance and tools to implement the OPEN Government Data Act.

While the site is required by the OPEN Government Data Act, resources.data.gov serves a broader purpose as the central repository for Federal Enterprise Data resources including tools, case studies, playbooks, and guidance on how to manage and use Federal data.  The repository will be frequently updated with additional tools and resources and will be developed in an open, collaborative manner and will welcome suggestions from the public.

**Comment by hkdctol** [comment]
@crysacarter can you follow up on the suggested edits to intro page - change to pull request?

**Comment by crysacarter** [comment]
Done

**Comment by adborden** [comment]
Thanks! Merged in https://github.com/GSA/resources.data.gov/pull/42
