### ISSUE TITLE
Remove licencing issues link 

### ISSUE THREAD

**Issue by crysacarter** [GSA/resources.data.gov#45]
Remove https://project-open-data.cio.gov/licensing-resources/

from https://resources.data.gov/skill-builders/

**Comment by crysacarter** [comment]
@adborden is there a new page to replace this with? or is that what I'm supposed to be doing? Creating a pull request for the new page?

**Comment by adborden** [comment]
I assumed we should just remove the link.

**Comment by crysacarter** [comment]
change made

**Comment by adborden** [comment]
@hkdctol to follow up

**Comment by mogul** [comment]
Looks like this was done but the issue was never closed.
