### ISSUE TITLE
Add information about interagency open data working group

### ISSUE THREAD

**Issue by philipashlock** [GSA/resources.data.gov#60]
explain what it is, how to get on listserv, calendar invite.

**Comment by hkdctol** [comment]
@crysacarter as discussed today, this information is in digital.gov under list of communities--can you draft the content for this and create PR--it would go on resources.data.gov

**Comment by crysacarter** [comment]
@crysacarter - reminder to add link to tools agency inventory page after page is created

**Comment by adborden** [comment]
This work was done.
