### ISSUE TITLE
Is a new version of DCAT-US being considered?

### ISSUE THREAD

**Issue by jqnatividad** [GSA/resources.data.gov#621]
The original [DCAT](https://www.w3.org/TR/2014/REC-vocab-dcat-20140116/) specification published 2014-01-16,  [DCAT-US v.1.1](https://resources.data.gov/resources/dcat-us/) was published later that year on 2014-11-06.

Since then, [DCAT 2](https://www.w3.org/TR/vocab-dcat-2/) was made a W3C recommendation in 2020-02-20. And [DCAT 3](https://www.w3.org/TR/vocab-dcat-3/) was published earlier this year 2023-03-07.

As it seems the [current harvesting mechanism is being modernized](https://github.com/GSA/datagov-harvesting-logic), are there any plans to update DCAT-US to align with DCAT 3, similar to the [DCAT-AP 3](https://semiceu.github.io/DCAT-AP/releases/3.0.0/) initiative?

**Comment by jqnatividad** [comment]
No I haven't @hkdctol. Thanks for the quick response!

There is a discussion on DCAT 3 on CKAN - https://github.com/ckan/ckan/discussions/7855 and https://github.com/ckan/ckanext-dcat/issues/257, and this would be a good thing to incorporate as the CKAN project looks into modernizing harvesting.

Speaking of which, I gather the current https://github.com/GSA/datagov-harvesting-logic initiative will still target DCAT-US v1.1, correct?

Looking at the DCAT-US 3.0 repo, I see there's a lot of activity and it's still WIP. Are there target milestones for the spec?

cc @thegostev @anuveyatsu @gavram

**Comment by hkdctol** [comment]
Yes for right now we're looking at DCAT 1.1. On target dates for the update--target to have this round of review and comments by November, but there are lots of things that need to happen before being able to implement outside scope of the current project schedule
