### ISSUE TITLE
Update How to get your data on data.gov

### ISSUE THREAD

**Issue by jbrown-xentity** [GSA/resources.data.gov#651]
The entire page needs a re-do and clarification of language. We also need to re-do the diagram, as it is no longer accurate (CSW isn't used anymore, but WAF is).
Need to provide 2 diagrams, 1 in an idealized workflow, and another as a "what data.gov technically needs to harvest" diagram.

**Comment by jbrown-xentity** [comment]
@hkdctol let me know what you think of this image, as far as styling goes... If you want a longer discussion, lets set aside some time. As a reminder, we are replacing [this](https://resources.data.gov/resources/data-gov-open-data-howto/#federated-metadata-harvest-architecture).

![Image](https://github.com/GSA/resources.data.gov/assets/26980513/53a648b0-054a-4b96-a751-421a036969b7)

**Comment by jbrown-xentity** [comment]
As an aside, building via LucidChart. Free for 3 images/documents, but they aren't shareable...

**Comment by hkdctol** [comment]
The chart is great--simple and clear

**Comment by hkdctol** [comment]
It should be, to the expected audience.

**Comment by hkdctol** [comment]
The needed text updates are in suggest mode in this google [doc](https://docs.google.com/document/d/1gbAOltT7aP1GrTIUvMOp0e8uHheRZ5LfzPRjAWz8ZuU/edit?usp=sharing) please add any edits in suggest mode.

**Comment by jbrown-xentity** [comment]
@hkdctol I took a deep dive, I made some general edits but have broader ideas. Let me know if you want this process to be quick; if so we can shelve it. If we want to streamline it further, let's setup a working session.

**Comment by jbrown-xentity** [comment]
Transitioned to [this doc](https://docs.google.com/document/d/1xO_YIWei3YKPG8nqLbq7Jd_WOBFPqnJQs4Tl0B5WU2c/edit), as we needed a fresh start. About halfway through content generation at the time of this writing...

**Comment by jbrown-xentity** [comment]
Round 2 of edits and content creation are complete on the [document](https://docs.google.com/document/d/1xO_YIWei3YKPG8nqLbq7Jd_WOBFPqnJQs4Tl0B5WU2c/edit). @GSA/data-gov-team this could use a review before go live. Essentially we are responsible for supporting how to get data on data.gov, so we should all be familiar with the public statements of how to do that...

**Comment by hkdctol** [comment]
Made edits to the current working [document](https://docs.google.com/document/d/1xO_YIWei3YKPG8nqLbq7Jd_WOBFPqnJQs4Tl0B5WU2c/edit?usp=sharing) @GSA/data-gov-team should review and we should target publishing for next week.

**Comment by hkdctol** [comment]
Would like to get a read through from @tdlowden and then get this closed out this week

**Comment by tdlowden** [comment]
Did a review and made a couple suggestions. I think it's clear and I could follow all the substance! My only suggestions were for readability.

**Comment by jbrown-xentity** [comment]
All the comments were great, thanks all! I feel ready to ship this, @hkdctol let me know what the next steps are...

**Comment by hkdctol** [comment]
Not sure what's going on with the title in the google doc: https://docs.google.com/document/d/1xO_YIWei3YKPG8nqLbq7Jd_WOBFPqnJQs4Tl0B5WU2c/edit?usp=sharing otherwise ready to go as replacement for current content at https://resources.data.gov/resources/data-gov-open-data-howto/ @jbrown-xentity

**Comment by hkdctol** [comment]
@jbrown-xentity were you going to get this new version on the existing link?

**Comment by jbrown-xentity** [comment]
@hkdctol if you want to take a look at https://github.com/GSA/resources.data.gov/pull/667 and review the published version on cloud.gov pages, then if it's good just merge it and this is done.
