### ISSUE TITLE
Update Metadata Schema to new link 

### ISSUE THREAD

**Issue by crysacarter** [GSA/resources.data.gov#68]
https://resources.data.gov/tools/

Link for schema still leads to POD page.

Should be https://resources.data.gov/schemas/dcat-us/v1.1/

**Comment by crysacarter** [comment]
link changed

**Comment by crysacarter** [comment]
I thought I'd updated this, but couldn't find it.  

Just fixed the link.

**Comment by adborden** [comment]
This is done.
