### ISSUE TITLE
Update current inventory.data.gov guide

### ISSUE THREAD

**Issue by hkdctol** [GSA/resources.data.gov#681]
The current guide on resources.data.gov https://resources.data.gov/resources/inventory-data-gov-guide/ requires some updates.

Required changes are marked in https://docs.google.com/document/d/1eyBvxMnBPxE4xlaN4BED_E74_T1_tVHbPjxSG2rKb4c/edit?usp=sharing

**Comment by tdlowden** [comment]
@hkdctol @crysacarter I reviewed and made suggestions as well, but feel free to adopt only what you feel is necessary. Main thing I did was reformat the metadata fields section into bullets for easier human parsing. 



![Image](https://github.com/GSA/resources.data.gov/assets/6556888/3fe2b1f9-6114-4d88-b783-199f2cab3f3d)
