### ISSUE TITLE
 Is there a valid updated CSV to be provided on the bureau code?

### ISSUE THREAD

**Issue by crysacarter** [GSA/resources.data.gov#69]
For bureau code, the PDF link is valid. CSV link is not (see screen shot)

https://resources.data.gov/schemas/dcat-us/v1.1/

![Screen Shot 2019-10-08 at 11 13 41 AM](https://user-images.githubusercontent.com/49877323/66415893-a278c480-e9ca-11e9-95de-5e6ec79fda6f.png)

**Comment by hkdctol** [comment]
@crysacarter can you compare the CSV that's currently available on https://project-open-data.cio.gov/v1.1/schema/#bureauCode
does it match the PDF? If so then it would just be a matter of making that same CSV downloadable from resources.data.gov

**Comment by crysacarter** [comment]
Currently neither of the  links on https://resources.data.gov/schemas/dcat-us/v1.1/  are working - returning a 404 error (for both pdf and csv)  

On the POD site, the csv link worked, the pdf did not.

**Comment by hkdctol** [comment]
@crysacarter right--so can you go to the old site, Project Open Data, see if the CSV that's there matches the PDF that's there.

**Comment by crysacarter** [comment]
#112 - done

**Comment by mogul** [comment]
Discussed this today... We think this is long-since resolved.
