### ISSUE TITLE
Creating Anchors in  Create inventory-data-gov-guide.md #72

### ISSUE THREAD

**Issue by crysacarter** [GSA/resources.data.gov#73]
I've tried several examples found on github forums or on markdown cheatsheets.  I was not able to find any to help me create an anchor from the table of contents to the appropriate section.

**Comment by hkdctol** [comment]
@adborden this was the issue that @crysacarter ran into. I believe she has created PRs to move the existing guides to resources page but was not able to create anchor from table of contents.

**Comment by adborden** [comment]
@crysacarter Jekyll is actually using the kramdown flavor of markdown. You should be able to create anchors with this syntax https://kramdown.gettalong.org/syntax.html#block-ials

```
# table of contents
- [chapter 1](#chapter-1)

## The first chapter
{:#chapter-1}

It was a beautiful morning...
```

Grab me on slack if it's still not working.

**Comment by adborden** [comment]
Paired with @crysacarter and I think we got this sorted out.
