### ISSUE TITLE
Resources.data.gov footer

### ISSUE THREAD

**Issue by calemelin** [GSA/resources.data.gov#75]
Change text from website footer from "Office of Government Information & Oversight" to "Office of Government Information Services."

**Comment by adborden** [comment]
Hey @calemelin, this is a simple change that you can make yourself if you feel inclined. You can edit the footer HTML from here: https://github.com/GSA/resources.data.gov/blob/develop/pages/_includes/footer.html#L30

Click the pencil icon to edit inline and create a new PR. Ping me if you get stuck!

**Comment by crysacarter** [comment]
pull request created
