### ISSUE TITLE
Resources.data.gov or resources.data.gov?

### ISSUE THREAD

**Issue by adborden** [GSA/resources.data.gov#76]
I'm seeing uses of Resources.data.gov and resources.data.gov when referring to the site. Is there a more appropriate title, like "Federal Enterprise Data Resources", so we don't have to refer to it by URL?

**Comment by adborden** [comment]
I think technically, the site's "title" is something more like "Federal Enterprise Data Resources" and resources.data.gov is the URL, so it should be lowercased.

**Comment by hkdctol** [comment]
@rebeccawilliams @adborden perhaps discuss at our next meeting and settle.

**Comment by juliaklindpaintner** [comment]
With the new version of the site, we have elevated the URL and made "Federal Enterprise Data Resources" the subtitle. We believe that resources.data.gov will be more recognizable and understandable, especially given folks' familiarity with data.gov. I would still recommend using lowercase when writing out resources.data.gov unless it's at the beginning of a sentence.
